# Generated by Django 4.2.2 on 2023-06-28 10:12

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_poster'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pfp',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to=users.models.pfp_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='films.film'),
        ),
    ]
