# Generated by Django 4.2.2 on 2023-06-28 10:12

from django.db import migrations, models
import films.models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, upload_to=films.models.poster_path),
        ),
    ]
